version: '3'
services:

  elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:6.2.2
      container_name: elasticsearch
      environment:
        - node.name=pocfilebeat
        - cluster.name=elasticsearch
        - discovery.type=single-node
      ports:
        - "9200:9200"
        - "9300:9300"
      networks:
        - redeLocal
  logstash:
      image: gabrielpellegrini/linux:logstash
      container_name: logstash
      command: logstash -f /etc/logstash/conf.d/logstash.conf
      volumes:
        - ./logstash:/etc/logstash/conf.d
        - ./logstash/patterns:/etc/logstash/conf.d/patterns
      networks:
        - redeLocal
      depends_on:
        - elasticsearch
  kibana:
      image: docker.elastic.co/kibana/kibana:6.2.2
      container_name: kibana
      ports:
        - "5601:5601"
      environment:
        - SERVER_NAME=kibana
        - ELASTICSEARCH_URL=http://elasticsearch:9200
      networks:
        - redeLocal
      depends_on:
        - elasticsearch
  beats:
    image: filebeat:latest
    container_name: filebeat
    volumes:
      - ./filebeat/fake-logs:/var/logs
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
    networks:
        - redeLocal
    depends_on:
      - elasticsearch
      - kibana
networks:
  redeLocal:
    driver: bridge
