version: '3'

services:
  node:
    build:
      context: .
      dockerfile: dockerfile
    #command: node_modules/.bin/nodemon --exec npm start
    tty: true
    stdin_open: true
    container_name: node
    ports:
      - 3050:3000
    volumes:
      - .:/home/app/portal
      - /home/app/portal/node_modules
    networks: 
      - default
networks:
  default:
    external:
      name: localNetwork



    