
filebeat:
  prospectors:
    -
        paths:
          - /log/log1.txt
        type: txt
        document_type: filebeat_log
        scan_frequency: 10s

output:
  logstash:
    hosts: ["logstash:5044"]
logging:
  files:
    rotateeverybytes: 10485760 # = 10MB
  selectors: ["*"]
  level: warning