version: '3'
services:
  elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:6.2.2
      container_name: elasticsearch
      environment:
        - node.name=pocfilebeat
        - cluster.name=elasticsearch
      ports:
        - "9200:9200"
        - "9300:9300"
      networks:
        - redeLocal
  kibana:
      image: docker.elastic.co/kibana/kibana:6.2.2
      container_name: kibana
      ports:
        - "5601:5601"
      environment:
        - SERVER_NAME=kibana
        - ELASTICSEARCH_URL=http://elasticsearch:9200
      networks:
        - redeLocal
      depends_on:
        - elasticsearch
  logstash:
      image: docker.elastic.co/logstash/logstash:6.2.2
      container_name: logstash
      command: logstash -f /etc/logstash/conf.d/logstash_filebeat.conf
      volumes:
        - ./logstash:/etc/logstash/conf.d
        - ./logstash/patterns:/opt/logstash/patterns
      networks:
        - redeLocal
      depends_on:
        - elasticsearch
  beats:
    image: docker.elastic.co/beats/filebeat:6.2.2
    container_name: beats
    volumes:
      - ./filebeat/filebeat.yml:/filebeat.yml
      - ../fake-logs:/var/log
    networks:
        - redeLocal
    depends_on:
      - logstash
      - kibana

networks:
  redeLocal:
    driver: bridge
